config/routes.rb
Rails.application.routes.draw do
  resources :spaces
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :sessions, only: [:create, :new]


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  constraints RootRouteConstraint.new do
    root 'spaces#index'
  end
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :space

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :group

  validates :title, presence: true
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :groups

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :username, presence: true

  has_many :spaces

  def self.authenticate email, password
    user = find_by email: email
    if user && user.authenticate(password)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized_response

  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :require_login

  private

  def current_user
    @current_user || User.find(session[:current_user_id]) if session[:current_user_id]
  end

  def require_login
    redirect_to new_session_path, alert: "Not Authorized!" unless current_user.present?
  end

  def not_authorized_response
    redirect_to root_url, error: 'You are not authorized to accesss this'
  end
end

app/controllers/concerns/space_retriever.rb
class SpaceRetriever

  def initialize space_id
    @space_id = space_id
  end

  def name
    space.name
  end

  def description
    space.description
  end

  def user_id
    space.user_id
  end

  def group_titles
    map_group_attribute :title
  end

  def group_descriptions
    map_group_attribute :description
  end

  private

  def space
    @space ||= Space.find(@space_id)
  end

  def map_group_attribute attribute
    groups.map(&attribute)
  end

  def groups
    @groups ||= space.groups
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:current_user_id] = user.id
      redirect_to root_url, notice: "Welcome Back!"
    else
      flash[:error] = "Could not log you in"
      redirect_to new_session_path
    end
  end

  def destroy
    @_current_user = session[:current_user_id] = nil
    redirect_to root_url, notice: "You've successfully logged out!"
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :require_login
  before_action :set_space, only: [:edit, :update, :destroy]

  rescue_from Pundit::NotAuthorizedError, with: :resource_not_found

  def index
    @spaces = policy_scope(Space)
  end

  def show
    @space = authorize SpaceRetriever.new(params[:id]), policy_class: SpacePolicy
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params.merge(user_id: current_user.id))
    if @space.save
      redirect_to @space, notice: 'Space was successfully created.'
    else
      render :new
    end
  end

  def update
    if @space.update(space_params)
      redirect_to @space, notice: 'Space was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @space.destroy
    redirect_to spaces_url, notice: 'Space was successfully destroyed.'
  end

  private
    def set_space
      @space = authorize Space.find(params[:id])
    end

    def space_params
      params.require(:space).permit(:name, :description)
    end

    def resource_not_found
      raise ActiveRecord::RecordNotFound
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:current_user_id] = nil
    redirect_to root_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = authorize User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def meta_description(page_meta_description)
    content_for(:meta_description) { page_meta_description }
  end

  def heading(page_heading)
    content_for(:heading) { page_heading }
  end

  def humanize_boolean(input)
    input ||= ''
    case input.to_s.downcase
    when 't', 'true'
      'Yes'
    else
      'No'
    end
  end

  def css_for_boolean(input)
    if input
      'success'
    else
      'danger'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
  def space_list_without_current(current_space)
    current_user.spaces.reject { |space| space.name == current_space }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <% unless key == :timedout %>
    <%= content_tag :div, class: "alert alert-dismissable alert-#{key}" do -%>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= msg %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<p class="text-muted">
  &copy; <%= Time.now.year.to_s %> Myassets - All rights reserved
</p>

app/views/layouts/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_UA'].present? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  // Enable 'Demographics and interest reports' in your analytics settings
  // ga('require', 'displayfeatures');

  // Enable 'Use enhanced link attribution' in your analytics settings
  // ga('require', 'linkid', 'linkid.js');

  ga('create', '<%= ENV["GOOGLE_ANALYTICS_UA"] %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'My Assets!', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to 'New Space', new_space_path %>
          <li><%= link_to 'Logout', logout_path %></li>
          <li><%= link_to current_user.email, current_user %></li>
        <% else %>
          <li><%= link_to 'Create Account', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title><%= yield :title %></title>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= yield :meta_description %>"/>

  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!--[if lt IE 9]>
  <script
      src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <script
      src="//cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
  <script
      src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
  <![endif]-->
</head>

<body>
  <%= render 'layouts/google_analytics' %>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <main role="main" class="container">
    <div class="page-header">
      <h1><%= yield :heading %></h1>
    </div>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </main>

  <footer>
    <hr/>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </footer>
</body>
</html>

app/views/pages/index.html.erb
<h1>My Assets</h1>

app/views/spaces/_form.html.erb
<%= form_with(model: space, local: true) do |form| %>
  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spaces/_space_menu_item.html.erb
<li><%= link_to space_menu_item.name, space_menu_item %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spaces</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.user_id %></td>
        <td><%= space.name %></td>
        <td><%= space.description %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to @space.name, @space, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render partial: "space_menu_item", collection: space_list_without_current(@space.name), as: :space_menu_item %>
      </ul>
    </div>
  </div>
</nav>

<p>
  <%= @space.description %>
</p>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>